// <auto-generated />
using System;
using LoanPortalAPIDev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanPortalAPIDev.Migrations
{
    [DbContext(typeof(AppPostgresDbContext))]
    [Migration("20240318190804_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoanPortalAPIDev.Data.PQLC_Loan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("actionedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("applicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("applicationName")
                        .HasColumnType("text");

                    b.Property<string>("clientNumber")
                        .HasColumnType("text");

                    b.Property<double>("existingLoanBalance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("lastSavedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("loanProduct")
                        .HasColumnType("text");

                    b.Property<double>("proposedLoanBalance")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("PQLC_Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
